CREATE TABLE `articles` (
  `uri` text COLLATE utf8_unicode_ci,
  `publisher` text COLLATE utf8_unicode_ci,
  `publish_date` datetime DEFAULT NULL,
  `scrape_date` datetime DEFAULT NULL,
  `category` text COLLATE utf8_unicode_ci,
  `title` text COLLATE utf8_unicode_ci,
  `subtitle` text COLLATE utf8_unicode_ci,
  `thumb` text COLLATE utf8_unicode_ci,
  `content` text CHARACTER SET utf8mb4,
  `article_type` text COLLATE utf8_unicode_ci,
  `article_photo` text COLLATE utf8_unicode_ci,
  `article_caption` text COLLATE utf8_unicode_ci,
  `article_video` text COLLATE utf8_unicode_ci,
  `article_insta` text COLLATE utf8_unicode_ci,
  `author_name` text COLLATE utf8_unicode_ci,
  `author_type` text COLLATE utf8_unicode_ci,
  `author_url` text COLLATE utf8_unicode_ci,
  `fblikes` int(11) DEFAULT NULL,
  `twlikes` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
